const stringReversal = require("./stringReversal");
const palindromeString = require("./palindrome");
const integerReversal = require("./integerReversal");
const maxChars = require("./maxChar");
const fizzBuzz = require("./fizzBuzz");
const arrayPushPop = require("./arrayPushPop");
const countDigits = require("./countDigits");
const factorial = require("./factorial");
const trailingZeroes = require("./trailingZeroes");
const hcf = require("./hcfGCD");
const queue = require("./queue");
const anagrams = require("./anagrams");
const removeDuplicateItemArray = require("./removDuplicateArray");
const capitalizeFirstCharacter = require("./capitalizeCharacter");
const fibonaaciSeries = require("./fibonacciSeries");
const recursiveFibonacciSeries = require("./recursiveFibonacciSeries");
const circularQueue = require("./circularQueue");
const linearSearchObj = require("./linearSearch");
const binarySearchObj = require("./binarySearch");
const ascSelectionSortObj = require('./ascendingSelectionSort');
const dscSelectionSortObj = require('./descendingSelectionSort');
console.log(ascSelectionSortObj.selectionSort(ascSelectionSortObj.arrayElement,ascSelectionSortObj.minPosition));
console.log(dscSelectionSortObj.selectionSort(dscSelectionSortObj.arrayElement,dscSelectionSortObj.minPosition));

