const stringReversal = require("./stringReversal");
const palindromeString = require("./palindrome");
const integerReversal = require("./integerReversal");
const maxChars = require("./maxChar");
const fizzBuzz = require("./fizzBuzz");
const arrayPushPop = require("./arrayPushPop");
const countDigits = require("./countDigits");
const factorial = require("./factorial");
const trailingZeroes = require("./trailingZeroes");
const hcf = require("./hcfGCD");
const queue = require("./queue");
const anagrams = require("./anagrams");
const removeDuplicateItemArray = require("./removDuplicateArray");
const capitalizeFirstCharacter = require("./capitalizeCharacter");
const fibonaaciSeries = require("./fibonacciSeries");
const recursiveFibonacciSeries = require("./recursiveFibonacciSeries");
const circularQueue = require("./circularQueue");
circularQueue.enque(90);
circularQueue.enque(80);
circularQueue.enque(10);
circularQueue.enque(20);
circularQueue.enque(30);
circularQueue.dequeue();
circularQueue.enque(40);
circularQueue.dequeue();
circularQueue.dequeue();
circularQueue.enque(88);
circularQueue.enque(99);
circularQueue.display();
