const stringReversal = require("./stringReversal");
const palindromeString = require("./palindrome");
const integerReversal = require("./integerReversal");
const maxChars = require("./maxChar");
const fizzBuzz = require("./fizzBuzz");
const arrayPushPop = require("./arrayPushPop");
const countDigits = require("./countDigits");
const factorial = require("./factorial");
const trailingZeroes = require("./trailingZeroes");
const hcf = require("./hcfGCD");
const queue = require("./queue");
const anagrams = require("./anagrams");
console.log(anagrams("bat", "atb"));
